[ansible_core]
python.version = python3
python.required = 3.9, 3.13

[ansible_es]
python.version = python3
python.required = 3.9, 3.13

[ansible_itsi]
python.version = python3
python.required = 3.9, 3.13
